// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdkIYPWzep2Hp7p5Dk7mH64576-35rDk',
    appId: '1:687786236451:web:ca407726d3fcec1121ef96',
    messagingSenderId: '687786236451',
    projectId: 'fir-karte-de067',
    authDomain: 'fir-karte-de067.firebaseapp.com',
    storageBucket: 'fir-karte-de067.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdfUOGvq43Z0dIiQoX99TBKfbmEP3XMQ',
    appId: '1:687786236451:android:f7b90d22625b232221ef96',
    messagingSenderId: '687786236451',
    projectId: 'fir-karte-de067',
    storageBucket: 'fir-karte-de067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVGvtSG3i8pQQqIBqCoP_R0Sox987MVg',
    appId: '1:687786236451:ios:6a0c8177fc9f822421ef96',
    messagingSenderId: '687786236451',
    projectId: 'fir-karte-de067',
    storageBucket: 'fir-karte-de067.appspot.com',
    androidClientId:
        '687786236451-1naksu4autp0vtkkssbe0rt9kl3a28a5.apps.googleusercontent.com',
    iosClientId:
        '687786236451-35p85bv7eqeh50eetp4lv70slce9g2hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoKarte',
  );
}
